language: python

python:
  - "3.5"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda env create -f requirements.txt python=3.5
  - source activate slo
  - python setup.py install

  - export MKLROOT=$CONDA_PREFIX

  - wget -O scan.h5 "https://drive.google.com/uc?export=download&id=0B3gFEmaelkOoZEtvU19reklkamM" # uwute4_lowres

script: pytest
